// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1bzxcjV6kGGiRq1leLYbKHAO2Sf7Se6U',
    appId: '1:585067857938:web:31f1207fb7146afe70f0cb',
    messagingSenderId: '585067857938',
    projectId: 'cleanlycleaners-12d2f',
    authDomain: 'cleanlycleaners-12d2f.firebaseapp.com',
    storageBucket: 'cleanlycleaners-12d2f.firebasestorage.app',
    measurementId: 'G-Z32DSEE32C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp-D4t0iRgbeJvW8gNYmxazRJqWfTpotY',
    appId: '1:585067857938:android:223d31feb42c9b8270f0cb',
    messagingSenderId: '585067857938',
    projectId: 'cleanlycleaners-12d2f',
    storageBucket: 'cleanlycleaners-12d2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2w_nVojfsm9siGJ8Iu4N-_ALtCJ8S_fQ',
    appId: '1:585067857938:ios:9e3619cfed76f1ff70f0cb',
    messagingSenderId: '585067857938',
    projectId: 'cleanlycleaners-12d2f',
    storageBucket: 'cleanlycleaners-12d2f.firebasestorage.app',
    iosBundleId: 'com.cleanly.task.app2026',
  );
}
